# Based on https://github.com/kubernetes/kubernetes/tree/release-1.3/examples/celery-rabbitmq
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-public
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
    component: rabbitmq
